const KEY='fritidsplaneraren-v3';
const START=8, END=17, HOUR=78;
const tools=[
 {e:'🎨',n:'Pyssel',p:'Inne',m:'Pysselmaterial'},
 {e:'⚽',n:'Fotboll',p:'Ute',m:'Bollar, koner, västar'},
 {e:'🌲',n:'Skogen',p:'Ute',m:'Vatten, första hjälpen'},
 {e:'🎲',n:'Brädspel',p:'Inne',m:'Brädspel'},
 {e:'🏃',n:'Hinderbana',p:'Ute',m:'Koner, rep, mattor'},
 {e:'🎬',n:'Film',p:'Inne',m:'Film, projektor'},
 {e:'📚',n:'Högläsning',p:'Inne',m:'Bok'},
 {e:'🧁',n:'Bakning',p:'Inne',m:'Ingredienser, förkläden'},
 {e:'🎵',n:'Dans & musik',p:'Inne',m:'Musik'},
 {e:'🍎',n:'Lunch',p:'Inne',m:'Matsal'}
];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{days:[],selected:null};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+Math.random();
const mins=t=>{const [h,m]=String(t||'08:00').split(':').map(Number);return h*60+m};
const time=m=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const dateLabel=d=>new Date(d+'T12:00').toLocaleDateString('sv-SE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
function normalize(){state.days.forEach(d=>{d.activities??=[];d.children??=0;d.type??='Övrigt';d.responsible??='';d.lunch??='11:30';d.snack??='14:30';d.notes??='';d.materials??='';d.todos??='';d.activities.forEach(a=>{a.id??=uid();a.start??='08:00';a.end??=time(mins(a.start)+60);a.placeType??='Inne';a.staff??='';a.description??='';a.material??='';a.emoji??='✦'})})}normalize();save();
function shell(){ $('#app').innerHTML=`<header class="top"><button class="logo" onclick="home()">Fritids<span>planeraren</span></button><div class="top-actions"><button onclick="window.print()">🖨️ Skriv ut</button><button onclick="exportWord()">📄 Word</button></div></header><main id="main"></main>`;render(); }
function home(){state.selected=null;save();render();}
function render(){if(state.selected){renderEditor()}else renderHome()}
function renderHome(){const days=state.days.slice().sort((a,b)=>a.date.localeCompare(b.date));$('#main').innerHTML=`<div class="page"><div class="home-head"><div><div class="kicker">Fritidsplanering</div><h1>Mina dagar</h1><p>Bygg dagen genom att dra aktiviteter till rätt tid.</p></div><button class="primary" onclick="newDay()">＋ Ny planering</button></div>${days.length?`<div class="plans">${days.map(d=>`<article class="plan" onclick="openDay('${d.id}')"><button class="plan-delete" onclick="event.stopPropagation();deleteDay('${d.id}')">🗑</button><div class="plan-date">${esc(dateLabel(d.date))}</div><h2>${esc(d.type)}</h2><div class="plan-meta"><span class="pill">${d.activities.length} aktiviteter</span>${d.children?`<span class="pill">${d.children} barn</span>`:''}<span class="pill">${esc(d.responsible||'Ingen ansvarig')}</span></div></article>`).join('')}</div>`:`<div class="empty"><div style="font-size:42px">🗓️</div><strong>Din första planering</strong><span>Skapa en dag och dra sedan in aktiviteter i schemat.</span><br><br><button class="primary" onclick="newDay()">Skapa första dagen</button></div>`}</div>`}
function newDay(){const last=state.days.slice().sort((a,b)=>b.date.localeCompare(a.date))[0];let d=new Date();if(last){d=new Date(last.date+'T12:00');d.setDate(d.getDate()+1)}const day={id:uid(),date:d.toISOString().slice(0,10),type:'Övrigt',children:0,responsible:'',activities:[],lunch:'11:30',snack:'14:30',notes:'',materials:'',todos:''};state.days.push(day);state.selected=day.id;save();renderEditor()}
function openDay(id){state.selected=id;save();renderEditor()}
function getDay(){return state.days.find(d=>d.id===state.selected)}
function renderEditor(){const d=getDay();if(!d)return home();const acts=[...d.activities].sort((a,b)=>mins(a.start)-mins(b.start));const rows=Array.from({length:END-START},(_,i)=>`<div class="hour-line"><span>${String(START+i).padStart(2,'0')}:00</span><i></i></div>`).join('');$('#main').innerHTML=`<div class="editor-page"><div class="editor-head"><div class="editor-title"><button class="icon-btn" onclick="home()">←</button><div><h1>${esc(dateLabel(d.date))}</h1><p>Dra aktiviteter. Klicka för att ändra.</p></div></div><div class="editor-actions"><button class="secondary" onclick="copyDay()">Kopiera dag</button><button class="primary" onclick="exportWord()">📄 Word</button></div></div><div class="day-info"><div class="field"><label>Datum</label><input type="date" value="${d.date}" onchange="dayChange('date',this.value)"></div><div class="field"><label>Typ</label><select onchange="dayChange('type',this.value)">${['Övrigt','Höstlov','Jullov','Sportlov','Påsklov','Sommarlov','Studiedag','Utflykt'].map(x=>`<option ${x===d.type?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Barn</label><input type="number" min="0" value="${d.children}" onchange="dayChange('children',this.value)"></div><div class="field"><label>Ansvarig</label><input value="${esc(d.responsible)}" placeholder="Namn" onchange="dayChange('responsible',this.value)"></div></div><div class="planner-layout"><aside class="palette"><h3>Aktiviteter</h3><p>Dra ett kort till önskad timme.</p><div class="palette-list">${tools.map((t,i)=>`<button class="tool" data-tool="${i}" onpointerdown="paletteDown(event,${i})"><span class="emoji">${t.e}</span><span><b>${esc(t.n)}</b><small>${esc(t.p)}</small></span></button>`).join('')}</div><div class="hint">💡 Ny aktivitet hamnar automatiskt på nästa lediga timme. Du kan sedan dra den vart du vill.</div></aside><section class="schedule-wrap"><div class="schedule" id="schedule" style="--hours:${END-START}">${rows}<div class="drop-line" id="dropLine"></div>${acts.map(block).join('')}</div></section></div><div class="below"><section class="card"><h3>🍎 Mat</h3><div class="food-row"><div class="field"><label>Lunch</label><input value="${esc(d.lunch)}" onchange="dayChange('lunch',this.value)"></div><div class="field"><label>Mellis</label><input value="${esc(d.snack)}" onchange="dayChange('snack',this.value)"></div></div></section><section class="card"><h3>📝 Övrigt</h3><textarea placeholder="Material, att göra eller viktig information..." onchange="dayChange('notes',this.value)">${esc(d.notes)}</textarea></section></div></div>`;attachScheduleEvents()}
function block(a){const top=(mins(a.start)-START*60)*(HOUR/60),height=Math.max(60,(mins(a.end)-mins(a.start))*(HOUR/60));const cls=a.placeType==='Ute'?'out':a.placeType==='Både'?'both':a.name==='Lunch'?'special':'';return `<article class="activity-block ${cls} ${height<75?'compact':''}" data-id="${a.id}" style="top:${top}px;height:${height}px"><div class="block-top"><span class="emoji">${esc(a.emoji||'✦')}</span><h3>${esc(a.name)}</h3><span class="time">${esc(a.start)}–${esc(a.end)}</span></div><div class="sub">${esc(a.placeType)}${a.staff?' · '+esc(a.staff):''}${a.material?' · '+esc(a.material):''}</div><button class="delete" onclick="event.stopPropagation();removeActivity('${a.id}')">×</button></article>`}
let drag=null;
function attachScheduleEvents(){document.querySelectorAll('.activity-block').forEach(el=>el.addEventListener('pointerdown',startDrag));const s=$('#schedule');s.addEventListener('pointermove',scheduleMove);s.addEventListener('pointerup',scheduleUp);s.addEventListener('pointercancel',cancelDrag)}
function startDrag(e){if(e.target.closest('.delete'))return;const el=e.currentTarget,a=getDay().activities.find(x=>x.id===el.dataset.id);if(!a)return;drag={kind:'move',id:a.id,startY:e.clientY,offset:(mins(a.start)-START*60)*(HOUR/60),duration:mins(a.end)-mins(a.start),moved:false};el.classList.add('dragging');el.setPointerCapture?.(e.pointerId);e.preventDefault()}
function paletteDown(e,i){if(e.button!==undefined&&e.button!==0)return;drag={kind:'new',tool:i,startY:e.clientY,moved:false};document.body.style.userSelect='none';e.preventDefault()}
function scheduleMove(e){if(!drag)return;const s=$('#schedule'),r=s.getBoundingClientRect();if(e.clientY<r.top||e.clientY>r.bottom)return;const y=e.clientY-r.top;const snapped=Math.max(0,Math.min((END-START)*HOUR-60,Math.round(y/HOUR)*HOUR));$('#dropLine').style.top=snapped+'px';if(Math.abs(e.clientY-drag.startY)>7)drag.moved=true}
function scheduleUp(e){if(!drag)return;const s=$('#schedule'),r=s.getBoundingClientRect();const inside=e.clientY>=r.top&&e.clientY<=r.bottom;const y=e.clientY-r.top;let start=START*60+Math.round(y/HOUR)*60;start=Math.max(START*60,Math.min((END-1)*60,start));if(drag.kind==='new'&&inside){const t=tools[drag.tool];addActivity({name:t.n,emoji:t.e,placeType:t.p,material:t.m,start:time(start),end:time(Math.min(END*60,start+60))})}else if(drag.kind==='move'&&inside&&drag.moved){const a=getDay().activities.find(x=>x.id===drag.id);if(a){let duration=drag.duration;start=Math.max(START*60,Math.min(END*60-duration,start));a.start=time(start);a.end=time(start+duration);save();renderEditor()}}cancelDrag()}
function cancelDrag(){document.querySelectorAll('.dragging').forEach(x=>x.classList.remove('dragging'));$('#dropLine')&&($('#dropLine').style.top='');drag=null;document.body.style.userSelect=''}
function addActivity(data={}){const d=getDay();if(!d)return;let start=data.start?mins(data.start):nextFree(d);let duration=data.end?Math.max(30,mins(data.end)-start):60;start=Math.max(START*60,Math.min(END*60-duration,start));d.activities.push({id:uid(),name:data.name||'Ny aktivitet',emoji:data.emoji||'✦',start:time(start),end:time(start+duration),placeType:data.placeType||'Inne',place:'Fritids',staff:'',material:data.material||'',description:''});save();renderEditor()}
function nextFree(d){let t=START*60;for(const a of [...d.activities].sort((a,b)=>mins(a.start)-mins(b.start))){if(t<mins(a.start))return t;t=Math.max(t,mins(a.end))}return Math.min(t,(END-1)*60)}
function removeActivity(id){const d=getDay();d.activities=d.activities.filter(a=>a.id!==id);save();renderEditor()}
function dayChange(k,v){const d=getDay();if(!d)return;d[k]=k==='children'?Number(v)||0:v;save();renderEditor()}
function copyDay(){const d=getDay();const c=JSON.parse(JSON.stringify(d));c.id=uid();c.activities=c.activities.map(a=>({...a,id:uid()}));const dt=new Date(d.date+'T12:00');dt.setDate(dt.getDate()+1);c.date=dt.toISOString().slice(0,10);state.days.push(c);state.selected=c.id;save();renderEditor()}
function deleteDay(id=state.selected){if(!confirm('Radera denna planering?'))return;state.days=state.days.filter(d=>d.id!==id);state.selected=null;save();renderHome()}
function openActivity(id){const a=getDay().activities.find(x=>x.id===id);if(!a)return;const backdrop=document.createElement('div');backdrop.className='modal-backdrop';backdrop.innerHTML=`<div class="modal"><h2>${esc(a.emoji)} Redigera aktivitet</h2><div class="modal-grid"><label>Aktivitet<input id="mn" value="${esc(a.name)}"></label><label>Plats<select id="mp"><option ${a.placeType==='Inne'?'selected':''}>Inne</option><option ${a.placeType==='Ute'?'selected':''}>Ute</option><option ${a.placeType==='Både'?'selected':''}>Både</option></select></label><label>Start<input id="ms" type="time" value="${a.start}"></label><label>Slut<input id="me" type="time" value="${a.end}"></label><label class="full">Personal<input id="mf" value="${esc(a.staff||'')}" placeholder="T.ex. Anna, Johan"></label><label class="full">Material<input id="mm" value="${esc(a.material||'')}"></label><label class="full">Beskrivning<textarea id="md">${esc(a.description||'')}</textarea></label></div><div class="modal-actions"><button class="danger" onclick="removeActivity('${a.id}');this.closest('.modal-backdrop').remove()">Radera</button><div class="modal-right"><button class="secondary" onclick="this.closest('.modal-backdrop').remove()">Avbryt</button><button class="primary" onclick="saveActivity('${a.id}',this.closest('.modal-backdrop'))">Spara</button></div></div></div>`;backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.remove()});document.body.appendChild(backdrop)}
function saveActivity(id,modal){const a=getDay().activities.find(x=>x.id===id);if(!a)return;a.name=$('#mn').value||'Ny aktivitet';a.placeType=$('#mp').value;a.start=$('#ms').value;a.end=$('#me').value;a.staff=$('#mf').value;a.material=$('#mm').value;a.description=$('#md').value;if(mins(a.end)<=mins(a.start))a.end=time(Math.min(END*60,mins(a.start)+60));save();modal.remove();renderEditor()}
function exportWord(){const d=getDay();if(!d){alert('Öppna en planering först.');return}if(!window.docx){alert('Word-exporten laddas fortfarande. Försök igen om en sekund.');return}const {Document,Packer,Paragraph,TextRun,HeadingLevel}=window.docx;const children=[new Paragraph({text:'Fritidsplanering',heading:HeadingLevel.TITLE}),new Paragraph({children:[new TextRun({text:dateLabel(d.date),bold:true})]}),new Paragraph(''),new Paragraph(`Typ: ${d.type}`),new Paragraph(`Barn: ${d.children}`),new Paragraph(`Ansvarig: ${d.responsible||'—'}`),new Paragraph(''),new Paragraph({text:'Schema',heading:HeadingLevel.HEADING_1})];d.activities.slice().sort((a,b)=>mins(a.start)-mins(b.start)).forEach(a=>children.push(new Paragraph({children:[new TextRun({text:`${a.start}–${a.end}  ${a.emoji||''} ${a.name}`,bold:true}),new TextRun({text:`  ${a.placeType}${a.staff?' · '+a.staff:''}`})]})));children.push(new Paragraph(''),new Paragraph({text:'Mat',heading:HeadingLevel.HEADING_1}),new Paragraph(`Lunch: ${d.lunch||'—'}`),new Paragraph(`Mellis: ${d.snack||'—'}`),new Paragraph(''),new Paragraph({text:'Övrigt',heading:HeadingLevel.HEADING_1}),new Paragraph(d.notes||'—'));Packer.toBlob(new Document({sections:[{children}]})).then(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Fritidsplanering-${d.date}.docx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)})}
window.newDay=newDay;window.openDay=openDay;window.home=home;window.deleteDay=deleteDay;window.removeActivity=removeActivity;window.copyDay=copyDay;window.dayChange=dayChange;window.exportWord=exportWord;window.paletteDown=paletteDown;window.saveActivity=saveActivity;document.addEventListener('click',e=>{const b=e.target.closest('.activity-block');if(b&&!drag?.moved)openActivity(b.dataset.id)});shell();
