/* Replaces the old drag patch: live block movement + week planning. */
(function(){
  const addDays=d=>n=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
  window.weekAddDays=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
  window.weekMonday=d=>{const x=new Date(d+'T12:00:00'),day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x.toISOString().slice(0,10)};
  window.showWeek=function(d){state.selected=null;state.weekDate=weekMonday(d||state.weekDate||new Date().toISOString().slice(0,10));save();renderWeek()};
  window.renderWeek=function(){const mon=state.weekDate,days=Array.from({length:7},(_,i)=>weekAddDays(mon,i));const html=days.map(d=>{const day=state.days.find(x=>x.date===d),acts=day?[...day.activities].sort((a,b)=>mins(a.start)-mins(b.start)):[];return `<section class="week-day ${day?'has-day':'empty-day'}"><button class="week-day-head" onclick="${day?`openDay('${day.id}')`:`createWeekDay('${d}')`}"><span>${new Date(d+'T12:00:00').toLocaleDateString('sv-SE',{weekday:'short',day:'numeric',month:'short'})}</span><b>${day?esc(day.type):'＋ Skapa dag'}</b></button>${day?acts.map(a=>`<button class="week-block" onclick="openDay('${day.id}')"><strong>${esc(a.emoji||'✦')} ${esc(a.name)}</strong><small>${a.start}–${a.end}</small></button>`).join(''):`<button class="week-add" onclick="createWeekDay('${d}')">＋ Lägg till dag</button>`}</section>`}).join('');document.getElementById('main').innerHTML=`<div class="week-page"><div class="week-head"><div><button class="back" onclick="home()">← Dagar</button><div class="kicker">Veckoöversikt</div><h1>Veckoplanering</h1><p>${esc(dateLabel(mon))} – ${esc(dateLabel(weekAddDays(mon,6)))}</p></div><div class="week-nav"><button class="secondary" onclick="showWeek(weekAddDays(state.weekDate,-7))">← Förra veckan</button><button class="secondary" onclick="showWeek(new Date().toISOString().slice(0,10))">Idag</button><button class="secondary" onclick="showWeek(weekAddDays(state.weekDate,7))">Nästa vecka →</button></div></div><div class="week-grid">${html}</div></div>`};
  window.createWeekDay=function(date){const d={id:uid(),date:date,type:'Övrigt',children:0,responsible:'',activities:[],lunch:'11:30',snack:'14:30',notes:''};state.days.push(d);state.selected=d.id;state.weekDate=null;save();renderEditor()};
  const oldRenderHome=window.renderHome;window.renderHome=function(){oldRenderHome();const head=document.querySelector('.home-head');if(head&&!head.querySelector('.week-home-btn')){const b=document.createElement('button');b.className='secondary week-home-btn';b.textContent='▦ Veckoplanering';b.onclick=()=>showWeek();head.appendChild(b)}};
  let drag=null;
  window.attachScheduleEvents=function(){const s=document.querySelector('#schedule');if(!s)return;document.querySelectorAll('.activity-block').forEach(el=>el.addEventListener('pointerdown',start));s.addEventListener('pointermove',move);s.addEventListener('pointerup',up);s.addEventListener('pointercancel',cancel);s.addEventListener('click',e=>{const b=e.target.closest('.activity-block');if(b&&!drag?.moved)openActivity(b.dataset.id)})};
  function start(e){if(e.target.closest('.delete'))return;const el=e.currentTarget,a=getDay().activities.find(x=>x.id===el.dataset.id);if(!a)return;drag={kind:'move',id:a.id,startY:e.clientY,base:(mins(a.start)-START*60)*(HOUR/60),duration:mins(a.end)-mins(a.start),moved:false,el};el.classList.add('dragging');el.setPointerCapture?.(e.pointerId);document.body.style.userSelect='none';e.preventDefault()}
  window.paletteDown=function(e,i){if(e.button!==undefined&&e.button!==0)return;const t=tools[i],g=document.createElement('div');g.className='drag-ghost';g.textContent=t.e+' '+t.n;document.body.appendChild(g);drag={kind:'new',tool:i,startY:e.clientY,moved:false,ghost:g};document.body.style.userSelect='none';e.preventDefault()};
  function move(e){if(!drag)return;const s=document.querySelector('#schedule'),r=s.getBoundingClientRect();drag.moved=drag.moved||Math.abs(e.clientY-drag.startY)>5;if(drag.kind==='new'){drag.ghost.style.left=e.clientX+14+'px';drag.ghost.style.top=e.clientY+14+'px'}if(e.clientY<r.top||e.clientY>r.bottom)return;const duration=drag.kind==='move'?drag.duration:60,start=Math.max(START*60,Math.min(END*60-duration,START*60+Math.round((e.clientY-r.top)/HOUR)*60)),top=(start-START*60)*(HOUR/60);const line=document.querySelector('#dropLine');if(line){line.style.top=top+'px';line.style.opacity='1'}if(drag.kind==='move')drag.el.style.transform=`translateY(${top-drag.base}px)`}
  function up(e){if(!drag)return;const s=document.querySelector('#schedule'),r=s.getBoundingClientRect(),inside=e.clientY>=r.top&&e.clientY<=r.bottom;if(inside){const duration=drag.kind==='move'?drag.duration:60,start=Math.max(START*60,Math.min(END*60-duration,START*60+Math.round((e.clientY-r.top)/HOUR)*60));if(drag.kind==='new'){const t=tools[drag.tool];addActivity({name:t.n,emoji:t.e,placeType:t.p,material:t.m,start:tm(start),end:tm(start+duration)})}else if(drag.moved){const a=getDay().activities.find(x=>x.id===drag.id);a.start=tm(start);a.end=tm(start+duration);save();renderEditor()}}cancel()}
  function cancel(){if(drag?.ghost)drag.ghost.remove();document.querySelectorAll('.dragging').forEach(x=>{x.classList.remove('dragging');x.style.transform='' });const line=document.querySelector('#dropLine');if(line){line.style.opacity='0';line.style.top=''}drag=null;document.body.style.userSelect=''}
})();
