const KEY='fritidsplanerare-v1';
const templates=[['🎨','Pyssel','Inne','Pysselmaterial'],['⚽','Fotboll','Ute','Fotbollar, koner, västar'],['🏃','Hinderbana','Ute','Koner, rep, mattor'],['🎲','Brädspel','Inne','Brädspel'],['🌲','Skogsutflykt','Ute','Första hjälpen, vatten'],['🎬','Film','Inne','Film, projektor'],['📚','Högläsning','Inne','Bok'],['🧁','Bakning','Inne','Ingredienser, förkläden'],['🎵','Dans & musik','Inne','Musik']];
let state=load();
function uid(){return (crypto&&crypto.randomUUID)?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object')return s}catch(e){}return {days:[],people:[],selected:null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function min(t){const p=String(t||'08:00').split(':').map(Number);return p[0]*60+p[1]}
function tm(m){m=Math.max(480,Math.min(1439,m));return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function today(){return new Date().toISOString().slice(0,10)}
function dayName(d){return new Date(d+'T12:00:00').toLocaleDateString('sv-SE',{weekday:'long'})}
function dateText(d){return new Date(d+'T12:00:00').toLocaleDateString('sv-SE',{day:'numeric',month:'long',year:'numeric'})}
function normalize(){if(!Array.isArray(state.days))state.days=[];if(!Array.isArray(state.people))state.people=[];state.days.forEach(d=>{d.id=d.id||uid();d.date=/^\d{4}-\d{2}-\d{2}$/.test(d.date)?d.date:today();d.type=d.type||'Övrigt';d.children=Number(d.children)||0;d.responsible=d.responsible||'';d.activities=Array.isArray(d.activities)?d.activities:[];d.materials=Array.isArray(d.materials)?d.materials:[];d.todos=Array.isArray(d.todos)?d.todos:[];d.activities.forEach(a=>{a.id=a.id||uid();a.start=a.start||'08:00';a.end=a.end||tm(min(a.start)+60);a.name=a.name||'Ny aktivitet';a.placeType=a.placeType||'Inne';a.place=a.place||'Fritids';a.group=a.group||'Alla';a.staff=Array.isArray(a.staff)?a.staff:[];a.material=a.material||'';a.description=a.description||'';a.safety=a.safety||''})});if(!state.days.some(d=>d.id===state.selected))state.selected=null}
normalize();save();
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const id={dashboard:'dashboardView',editor:'editorView',week:'weekView',templates:'templatesView',people:'peopleView'}[view];document.getElementById(id)?.classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view||view==='editor'&&n.dataset.view==='dashboard'))}
function render(){renderStats();renderDays();renderWeek();renderTemplates();renderPeople();if(state.selected)renderEditor()}
function renderStats(){const e=document.getElementById('stats');if(!e)return;const acts=state.days.reduce((n,d)=>n+d.activities.length,0),out=state.days.reduce((n,d)=>n+d.activities.filter(a=>a.placeType==='Ute').length,0);e.innerHTML=`<div class="stat"><b>${state.days.length}</b><span>Dagar</span></div><div class="stat"><b>${acts}</b><span>Aktiviteter</span></div><div class="stat"><b>${out}</b><span>Ute</span></div><div class="stat"><b>${state.people.length}</b><span>Personal</span></div>`}
function renderDays(){const e=document.getElementById('daysList');if(!e)return;const days=state.days.slice().sort((a,b)=>a.date.localeCompare(b.date));if(!days.length){e.innerHTML='<div class="empty"><div class="empty-icon">＋</div><h3>Din planeringsvecka börjar här</h3><p>Skapa en dag och bygg schemat steg för steg. Inga dragzoner, inga konstigheter.</p><button class="primary big" onclick="newDay()">Skapa första dagen</button></div>';return}e.innerHTML=days.map((d,i)=>`<article class="day-card"><button class="day-main" onclick="openDay('${d.id}')"><div class="day-number">${String(new Date(d.date+'T12:00:00').getDate()).padStart(2,'0')}</div><div class="day-info"><div class="day-title">${esc(dayName(d.date))}</div><div class="day-meta">${esc(dateText(d.date))} · ${esc(d.type)}</div><div class="day-chips">${d.activities.slice().sort((a,b)=>min(a.start)-min(b.start)).slice(0,4).map(a=>`<span>${esc(a.start)} ${esc(a.name)}</span>`).join('')}${d.activities.length>4?`<span>+${d.activities.length-4}</span>`:''}</div></div><div class="open-arrow">→</div></button><button class="delete-day" title="Radera dag" onclick="event.stopPropagation();deleteDay('${d.id}')">🗑</button></article>`).join('')}
function nextTimes(d){if(!d.activities.length)return['08:00','09:00'];const end=Math.max(...d.activities.map(a=>min(a.end)));return[tm(end),tm(end+60)]}
function renderEditor(){const d=state.days.find(x=>x.id===state.selected),e=document.getElementById('editorView');if(!d||!e)return;const acts=d.activities.slice().sort((a,b)=>min(a.start)-min(b.start));e.innerHTML=`<div class="planner"><div class="planner-top"><button class="back" onclick="closeEditor()">← Alla dagar</button><div class="planner-actions"><button class="ghost" onclick="copyDay()">Kopiera</button><button class="primary" onclick="exportWord()">Exportera Word</button></div></div><div class="day-hero"><div><span class="eyebrow">PLANERINGSKORT</span><h1>${esc(dayName(d.date))}</h1><p>${esc(dateText(d.date))} · ${esc(d.type)}</p></div><div class="hero-date"><label>DATUM</label><input type="date" value="${d.date}" onchange="updateDay('date',this.value)"></div></div><div class="quick-fields"><label><span>TYP</span><select onchange="updateDay('type',this.value)">${['Övrigt','Höstlov','Jullov','Sportlov','Påsklov','Sommarlov','Studiedag'].map(x=>`<option ${d.type===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>BARN</span><input type="number" min="0" value="${d.children}" onchange="updateDay('children',this.value)"></label><label><span>ANSVARIG</span><input value="${esc(d.responsible)}" placeholder="Namn" onchange="updateDay('responsible',this.value)"></label><label class="wide"><span>NOTERING</span><input value="${esc(d.notes||'')}" placeholder="Viktig info för dagen" onchange="updateDay('notes',this.value)"></label></div><div class="section-head"><div><span class="eyebrow">DAGENS FLÖDE</span><h2>Schema</h2><p>Nästa aktivitet får automatiskt nästa lediga timme.</p></div><button class="primary" onclick="addActivity()">＋ Lägg till aktivitet</button></div><div class="timeline">${acts.map(activityHtml).join('')||'<div class="timeline-empty">08:00<br><strong>Ingen aktivitet ännu</strong><button class="secondary" onclick="addActivity()">Lägg till 08:00</button></div>'}</div><div class="two-cols"><section class="panel"><div class="panel-head"><h3>🍎 Mat</h3></div><div class="fields2"><label>Lunch<input value="${esc(d.lunch||'11:30 – Matsal')}" onchange="updateDay('lunch',this.value)"></label><label>Mellis<input value="${esc(d.snack||'14:30 – Fritids')}" onchange="updateDay('snack',this.value)"></label><label class="full">Specialkost / kommentar<input value="${esc(d.foodNotes||'')}" onchange="updateDay('foodNotes',this.value)"></label></div></section><section class="panel"><div class="panel-head"><h3>🧰 Förberedelser</h3></div><label>Material, en rad per sak<textarea onchange="updateDay('materials',this.value)">${esc(d.materials.join('\n'))}</textarea></label><label>Att göra, en rad per sak<textarea onchange="updateDay('todos',this.value)">${esc(d.todos.join('\n'))}</textarea></label></section></div><div class="danger-zone"><span>Färdig med dagen?</span><button class="danger" onclick="deleteDay('${d.id}')">Radera denna dag</button></div></div>`}
function activityHtml(a){return`<article class="activity-row"><div class="activity-time"><input type="time" value="${a.start}" onchange="updateActivity('${a.id}','start',this.value)"><b>–</b><input type="time" value="${a.end}" onchange="updateActivity('${a.id}','end',this.value)"></div><div class="activity-icon ${a.placeType==='Ute'?'out':''}">${a.placeType==='Ute'?'☀':'✦'}</div><div class="activity-main"><input class="activity-name" value="${esc(a.name)}" onchange="updateActivity('${a.id}','name',this.value)"><div class="activity-sub"><button class="tag" onclick="cyclePlace('${a.id}')">${esc(a.placeType)}</button><span>${esc(a.place)}</span><span>${esc(a.staff.join(', ')||'Ingen personal')}</span></div></div><button class="more" onclick="toggleDetails('${a.id}')">⋯</button><button class="remove" onclick="removeActivity('${a.id}')">×</button><div class="details" id="details-${a.id}"><label>Plats<input value="${esc(a.place)}" onchange="updateActivity('${a.id}','place',this.value)"></label><label>Grupp<input value="${esc(a.group)}" onchange="updateActivity('${a.id}','group',this.value)"></label><label>Personal<input value="${esc(a.staff.join(', '))}" onchange="updateActivity('${a.id}','staff',this.value.split(',').map(x=>x.trim()).filter(Boolean))"></label><label>Material<input value="${esc(a.material)}" onchange="updateActivity('${a.id}','material',this.value)"></label><label class="full">Beskrivning<textarea onchange="updateActivity('${a.id}','description',this.value)">${esc(a.description)}</textarea></label><label class="full">Förberedelser / säkerhet<textarea onchange="updateActivity('${a.id}','safety',this.value)">${esc(a.safety)}</textarea></label></div></article>`}
function addActivity(data={}){const d=state.days.find(x=>x.id===state.selected);if(!d)return;const t=data.start? [data.start,data.end]:nextTimes(d);d.activities.push({id:uid(),start:t[0],end:t[1],name:data.name||'Ny aktivitet',placeType:data.placeType||'Inne',place:data.place||'Fritids',group:data.group||'Alla',staff:data.staff||[],material:data.material||'',description:'',safety:''});save();renderEditor();renderStats()}
function addTemplate(i){const t=templates[i];addActivity({name:t[1],placeType:t[2],material:t[3]})}
function cyclePlace(id){const a=find(id);if(!a)return;a.placeType=a.placeType==='Inne'?'Ute':a.placeType==='Ute'?'Både':'Inne';save();renderEditor()}
function find(id){const d=state.days.find(x=>x.id===state.selected);return d&&d.activities.find(a=>a.id===id)}
function updateActivity(id,k,v){const a=find(id);if(!a)return;a[k]=v;if(k==='start'&&min(a.end)<=min(v))a.end=tm(min(v)+60);if(k==='end'&&min(v)<=min(a.start))a.end=tm(min(a.start)+60);save();renderEditor()}
function removeActivity(id){const d=state.days.find(x=>x.id===state.selected);if(!d)return;d.activities=d.activities.filter(a=>a.id!==id);save();renderEditor();renderStats()}
function toggleDetails(id){document.getElementById('details-'+id)?.classList.toggle('open')}
function newDay(){const sorted=state.days.slice().sort((a,b)=>b.date.localeCompare(a.date));let dt=new Date();if(sorted[0]){dt=new Date(sorted[0].date+'T12:00:00');dt.setDate(dt.getDate()+1)}const d={id:uid(),date:dt.toISOString().slice(0,10),type:'Övrigt',children:0,responsible:'',activities:[],lunch:'11:30 – Matsal',snack:'14:30 – Fritids',materials:[],todos:[],notes:'',foodNotes:''};state.days.push(d);state.selected=d.id;save();show('editor');render()}
function openDay(id){if(!state.days.some(d=>d.id===id))return;state.selected=id;save();show('editor');renderEditor()}
function closeEditor(){state.selected=null;save();show('dashboard');render()}
function updateDay(k,v){const d=state.days.find(x=>x.id===state.selected);if(!d)return;d[k]=['materials','todos'].includes(k)?String(v).split('\n').map(x=>x.trim()).filter(Boolean):k==='children'?Number(v)||0:v;save();renderEditor();renderStats()}
function deleteDay(id){const d=state.days.find(x=>x.id===id);if(!d)return;if(!confirm(`Radera ${dayName(d.date)} ${dateText(d.date)}? Detta går inte att ångra.`))return;state.days=state.days.filter(x=>x.id!==id);if(state.selected===id)state.selected=null;save();show('dashboard');render()}
function copyDay(){const d=state.days.find(x=>x.id===state.selected);if(!d)return;const c=JSON.parse(JSON.stringify(d));c.id=uid();c.activities=c.activities.map(a=>({...a,id:uid()}));const dt=new Date(d.date+'T12:00:00');dt.setDate(dt.getDate()+1);c.date=dt.toISOString().slice(0,10);state.days.push(c);state.selected=c.id;save();render()}
function renderWeek(){const e=document.getElementById('weekGrid');if(!e)return;e.innerHTML=state.days.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(d=>`<div class="week-card"><div class="week-date">${new Date(d.date+'T12:00:00').getDate()}</div><h3>${esc(dayName(d.date))}</h3><small>${esc(dateText(d.date))}</small>${d.activities.slice().sort((a,b)=>min(a.start)-min(b.start)).map(a=>`<div class="week-item"><b>${a.start}–${a.end}</b><br>${esc(a.name)}</div>`).join('')||'<p>Tom dag</p>'}</div>`).join('')||'<div class="empty">Ingen dagar ännu.</div>'}
function renderTemplates(){const e=document.getElementById('templatesGrid');if(!e)return;e.innerHTML=templates.map((t,i)=>`<button class="template-card" onclick="state.selected?addTemplate(${i}):newDay()"><span>${t[0]}</span><b>${esc(t[1])}</b><small>${esc(t[2])} · ${esc(t[3])}</small></button>`).join('')}
function renderPeople(){const e=document.getElementById('peopleList');if(!e)return;e.innerHTML=state.people.map((p,i)=>`<div class="person-card"><b>${esc(p)}</b><button onclick="state.people.splice(${i},1);save();renderPeople();renderStats()">×</button></div>`).join('')||'<div class="empty">Lägg till personal för att kunna välja dem på aktiviteter.</div>'}
function download(name,data,type){const b=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function exportWord(){const d=state.days.find(x=>x.id===state.selected);if(!d)return alert('Öppna en dag först.');if(!window.docx)return alert('Word-biblioteket kunde inte laddas. Ladda om sidan.');try{const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,HeadingLevel}=window.docx;const cell=x=>new TableCell({children:[new Paragraph({children:[new TextRun({text:String(x||'—')})]})]});const rows=[new TableRow({children:['Tid','Aktivitet','Inne/Ute','Plats','Personal'].map(x=>new TableCell({children:[new Paragraph({children:[new TextRun({text:x,bold:true})]})]}))}),...d.activities.slice().sort((a,b)=>min(a.start)-min(b.start)).map(a=>new TableRow({children:[cell(a.start+'–'+a.end),cell(a.name),cell(a.placeType),cell(a.place),cell(a.staff.join(', '))]}))];const doc=new Document({sections:[{children:[new Paragraph({text:'FRITIDSPLANERING',heading:HeadingLevel.TITLE}),new Paragraph({text:dayName(d.date)+' · '+dateText(d.date)}),new Paragraph({text:`${d.type} · ${d.children} barn · Ansvarig: ${d.responsible||'—'}`}),new Paragraph({text:'Schema',heading:HeadingLevel.HEADING_1}),new Table({rows,width:{size:100,type:WidthType.PERCENTAGE}}),new Paragraph({text:'Lunch: '+(d.lunch||'—')}),new Paragraph({text:'Mellis: '+(d.snack||'—')})]}]});const blob=await Packer.toBlob(doc);download('Fritidsplanering-'+d.date+'.docx',blob,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}catch(e){console.error(e);alert('Word-exporten misslyckades: '+e.message)}}
function wire(){document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{show(n.dataset.view);render()});['newDay','newDay2'].forEach(id=>document.getElementById(id)?.addEventListener('click',newDay));document.getElementById('printBtn')?.addEventListener('click',()=>print());document.getElementById('exportWord')?.addEventListener('click',exportWord);document.getElementById('exportJson')?.addEventListener('click',()=>download('fritidsplanering.json',JSON.stringify(state,null,2),'application/json'));document.getElementById('addPerson')?.addEventListener('click',()=>{const n=prompt('Namn på personal');if(n?.trim()){state.people.push(n.trim());save();renderPeople();renderStats()}});document.getElementById('importJson')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);normalize();save();show('dashboard');render()}catch(err){alert('Filen kunde inte läsas.')}};r.readAsText(f)})}
wire();show(state.selected?'editor':'dashboard');render();